# config_train.yaml

WORK:
  PATH: "/home/user/work/mnist/"
              
DATA:
  PATH: "/home/user/work/mnist/data/"
  RAW_PATH: "/home/user/work/mnist/data/MNIST/raw/"
  PROCESSED_PATH: "/home/user/work/mnist/data/MNIST/processed/"

TRAIN:
  BATCH_SIZE: 100
  INPUT_SIZE: 784
  HIDDEN_SIZE1: 128
  HIDDEN_SIZE2: 64
  NUM_CLASSES: 10
  NUM_EPOCHS: 3
  LEARNING_RATE: 0.002
  MOMENTUM: 0.9
