# config_train.yaml

WORK:
  ROOT_PATH: "D:\\GitWork\\mnist\\"
  # ROOT_PATH: "/home/user/work/mnist/"
              
DATA:
  RAW_PATH: "D:\\GitWork\\mnist\\raw\\"
  # RAW_PATH: "/home/user/work/mnist/raw/"
  PROCESSED_PATH: "D:\\GitWork\\mnist\\raw\\"
  # PROCESSED_PATH: "/home/user/work/mnist/processed/"

TRAIN:
  BATCH_SIZE: 100
  INPUT_SIZE: 784
  HIDDEN_SIZE1: 128
  HIDDEN_SIZE2: 64
  NUM_CLASSES: 10
  EPOCHES: 3
  LEARNING_RATE: 0.002
  MOMENTUM: 0.9
